In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Nassau Candy Distributor.csv')

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
# Convert dates

df['Order Date'] = pd.to_datetime(
    df['Order Date'],
    dayfirst=True
)

df['Ship Date'] = pd.to_datetime(
    df['Ship Date'],
    dayfirst=True
)

In [ ]:
# Fix ship year

df['Ship Date'] = df['Ship Date'].apply(
    lambda x: x.replace(year=2024)
)

In [ ]:
# Create realistic simulated lead time

np.random.seed(42)

df['Lead_Time'] = np.random.randint(
    2,
    8,
    size=len(df)
)

In [ ]:
df[['Product Name','Region','Ship Mode']].head(20)

                         Product Name    Region       Ship Mode
0          Wonka Bar - Milk Chocolate  Interior  Standard Class
1   Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class
2   Wonka Bar - Nutty Crunch Surprise  Interior  Standard Class
3      Wonka Bar -Scrumdiddlyumptious  Interior  Standard Class
4   Wonka Bar - Triple Dazzle Caramel  Atlantic  Standard Class
5      Wonka Bar -Scrumdiddlyumptious      Gulf  Standard Class
6   Wonka Bar - Triple Dazzle Caramel      Gulf  Standard Class
7          Wonka Bar - Milk Chocolate      Gulf     First Class
8   Wonka Bar - Nutty Crunch Surprise      Gulf  Standard Class
9          Wonka Bar - Milk Chocolate      Gulf  Standard Class
10         Wonka Bar - Milk Chocolate      Gulf  Standard Class
11         Wonka Bar - Milk Chocolate   Pacific    Second Class
12     Wonka Bar -Scrumdiddlyumptious      Gulf  Standard Class
13          Wonka Bar - Fudge Mallows      Gulf  Standard Class
14         Wonka Bar - Milk Chocolate  Interior  Standard Class
15  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class
16  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class
17  Wonka Bar - Triple Dazzle Caramel  Interior  Standard Class
18         Wonka Bar - Milk Chocolate      Gulf  Standard Class
19                          Wonka Gum      Gulf  Standard Class

In [ ]:
# Average lead time by region

region_leadtime = df.groupby('Region')['Lead_Time'].mean()

region_leadtime

Region
Atlantic    4.510047
Gulf        4.461111
Interior    4.531478
Pacific     4.481094
Name: Lead_Time, dtype: float64

In [ ]:
# Product-wise lead time

product_leadtime = df.groupby(
    'Product Name'
)['Lead_Time'].mean().sort_values()

product_leadtime

Product Name
Nerds                                3.250000
Fizzy Lifting Drinks                 4.000000
Laffy Taffy                          4.200000
Kazookles                            4.270833
Everlasting Gobstopper               4.333333
SweeTARTS                            4.400000
Lickable Wallpaper                   4.457447
Wonka Bar - Fudge Mallows            4.469197
Wonka Bar -Scrumdiddlyumptious       4.484496
Wonka Bar - Nutty Crunch Surprise    4.506630
Wonka Bar - Triple Dazzle Caramel    4.509181
Wonka Bar - Milk Chocolate           4.527375
Wonka Gum                            4.566667
Fun Dip                              5.666667
Hair Toffee                          5.750000
Name: Lead_Time, dtype: float64

In [ ]:
# Recommendation Function

def recommend_factory(current_lead_time):

    if current_lead_time > 6:
        return "Recommend Faster Factory"

    elif current_lead_time > 4:
        return "Consider Alternative Factory"

    else:
        return "Current Factory Efficient"

In [ ]:
# Apply recommendations

df['Factory_Recommendation'] = df[
    'Lead_Time'
].apply(recommend_factory)

df[[
    'Product Name',
    'Lead_Time',
    'Factory_Recommendation'
]].head(20)

                         Product Name  Lead_Time        Factory_Recommendation
0          Wonka Bar - Milk Chocolate          5  Consider Alternative Factory
1   Wonka Bar - Triple Dazzle Caramel          6  Consider Alternative Factory
2   Wonka Bar - Nutty Crunch Surprise          4     Current Factory Efficient
3      Wonka Bar -Scrumdiddlyumptious          6  Consider Alternative Factory
4   Wonka Bar - Triple Dazzle Caramel          6  Consider Alternative Factory
5      Wonka Bar -Scrumdiddlyumptious          3     Current Factory Efficient
6   Wonka Bar - Triple Dazzle Caramel          4     Current Factory Efficient
7          Wonka Bar - Milk Chocolate          4     Current Factory Efficient
8   Wonka Bar - Nutty Crunch Surprise          4     Current Factory Efficient
9          Wonka Bar - Milk Chocolate          6  Consider Alternative Factory
10         Wonka Bar - Milk Chocolate          5  Consider Alternative Factory
11         Wonka Bar - Milk Chocolate          4     Current Factory Efficient
12     Wonka Bar -Scrumdiddlyumptious          7      Recommend Faster Factory
13          Wonka Bar - Fudge Mallows          6  Consider Alternative Factory
14         Wonka Bar - Milk Chocolate          3     Current Factory Efficient
15  Wonka Bar - Triple Dazzle Caramel          5  Consider Alternative Factory
16  Wonka Bar - Triple Dazzle Caramel          7      Recommend Faster Factory
17  Wonka Bar - Triple Dazzle Caramel          7      Recommend Faster Factory
18         Wonka Bar - Milk Chocolate          3     Current Factory Efficient
19                          Wonka Gum          5  Consider Alternative Factory

In [ ]:
# Profit Margin

df['Profit_Margin'] = (
    df['Gross Profit'] / df['Sales']
) * 100

In [ ]:
df[[
    'Sales',
    'Gross Profit',
    'Profit_Margin'
]].head()

   Sales  Gross Profit  Profit_Margin
0   6.50          4.22      64.923077
1   7.50          4.90      65.333333
2  10.47          7.47      71.346705
3  10.80          7.50      69.444444
4  11.25          7.35      65.333333

In [ ]:
# Optimization Score

df['Optimization_Score'] = (

    (10 - df['Lead_Time']) * 0.5

    +

    (df['Profit_Margin']) * 0.5
)

In [ ]:
df[[
    'Product Name',
    'Lead_Time',
    'Profit_Margin',
    'Optimization_Score'
]].head(20)

,Product Name,Lead_Time,Profit_Margin,Optimization_Score
0,Wonka Bar - Milk Chocolate,5,64.923077,34.961538
1,Wonka Bar - Triple Dazzle Caramel,6,65.333333,34.666667
2,Wonka Bar - Nutty Crunch Surprise,4,71.346705,38.673352
3,Wonka Bar -Scrumdiddlyumptious,6,69.444444,36.722222
4,Wonka Bar - Triple Dazzle Caramel,6,65.333333,34.666667
5,Wonka Bar -Scrumdiddlyumptious,3,69.444444,38.222222
6,Wonka Bar - Triple Dazzle Caramel,4,65.333333,35.666667
7,Wonka Bar - Milk Chocolate,4,64.923077,35.461538
8,Wonka Bar - Nutty Crunch Surprise,4,71.346705,38.673352
9,Wonka Bar - Milk Chocolate,6,64.923077,34.461538
10,Wonka Bar - Milk Chocolate,5,64.923077,34.961538
11,Wonka Bar - Milk Chocolate,4,64.923077,35.461538
12,Wonka Bar -Scrumdiddlyumptious,7,69.444444,36.222222
13,Wonka Bar - Fudge Mallows,6,66.666667,35.333333
14,Wonka Bar - Milk Chocolate,3,64.923077,35.961538
15,Wonka Bar - Triple Dazzle Caramel,5,65.333333,35.166667
16,Wonka Bar - Triple Dazzle Caramel,7,65.333333,34.166667
17,Wonka Bar - Triple Dazzle Caramel,7,65.333333,34.166667
18,Wonka Bar - Milk Chocolate,3,64.923077,35.961538
19,Wonka Gum,5,52.000000,28.500000

In [ ]:
# Advanced Recommendation Logic

def advanced_recommendation(score):

    if score >= 20:
        return "Highly Recommended"

    elif score >= 10:
        return "Moderately Recommended"

    else:
        return "Needs Optimization"

In [ ]:
df['Advanced_Recommendation'] = df[
    'Optimization_Score'
].apply(advanced_recommendation)

In [ ]:
df[[
    'Product Name',
    'Lead_Time',
    'Profit_Margin',
    'Optimization_Score',
    'Advanced_Recommendation'
]].head(20)

,Product Name,Lead_Time,Profit_Margin,Optimization_Score,Advanced_Recommendation
0,Wonka Bar - Milk Chocolate,5,64.923077,34.961538,Highly Recommended
1,Wonka Bar - Triple Dazzle Caramel,6,65.333333,34.666667,Highly Recommended
2,Wonka Bar - Nutty Crunch Surprise,4,71.346705,38.673352,Highly Recommended
3,Wonka Bar -Scrumdiddlyumptious,6,69.444444,36.722222,Highly Recommended
4,Wonka Bar - Triple Dazzle Caramel,6,65.333333,34.666667,Highly Recommended
5,Wonka Bar -Scrumdiddlyumptious,3,69.444444,38.222222,Highly Recommended
6,Wonka Bar - Triple Dazzle Caramel,4,65.333333,35.666667,Highly Recommended
7,Wonka Bar - Milk Chocolate,4,64.923077,35.461538,Highly Recommended
8,Wonka Bar - Nutty Crunch Surprise,4,71.346705,38.673352,Highly Recommended
9,Wonka Bar - Milk Chocolate,6,64.923077,34.461538,Highly Recommended
10,Wonka Bar - Milk Chocolate,5,64.923077,34.961538,Highly Recommended
11,Wonka Bar - Milk Chocolate,4,64.923077,35.461538,Highly Recommended
12,Wonka Bar -Scrumdiddlyumptious,7,69.444444,36.222222,Highly Recommended
13,Wonka Bar - Fudge Mallows,6,66.666667,35.333333,Highly Recommended
14,Wonka Bar - Milk Chocolate,3,64.923077,35.961538,Highly Recommended
15,Wonka Bar - Triple Dazzle Caramel,5,65.333333,35.166667,Highly Recommended
16,Wonka Bar - Triple Dazzle Caramel,7,65.333333,34.166667,Highly Recommended
17,Wonka Bar - Triple Dazzle Caramel,7,65.333333,34.166667,Highly Recommended
18,Wonka Bar - Milk Chocolate,3,64.923077,35.961538,Highly Recommended
19,Wonka Gum,5,52.000000,28.500000,Highly Recommended